# Generated by Django 3.2.4 on 2021-06-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('branch_name', models.CharField(max_length=60)),
                ('phone_no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='Restaurant.restaurant')),
            ],
        ),
    ]
