# Generated by Django 3.2.4 on 2021-06-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='user',
            new_name='user_id',
        ),
    ]
